version: 2.1

jobs:
  test:
    docker:
      - image: golang
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: sample job
          command: |
            sleep 10
            echo "this is sample"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
